feat: add archive projects to project service/slice
techmatters/terraso-client-shared pull request #64
Opened 2023-08-08 17:47 UTC by jodiezhuu

## Description
Add archive project service and archive project slice

2023-08-10 16:12 UTC, josebui requested changes

2023-08-10 16:12 UTC, josebui commented on package.json
> +    "terraso-backend": "github:techmatters/terraso-backend#a431376f71fe8537df6976cf8c2f6772e8d659af",
Question: Is this a commit that is already in the backend `main` branch?
Suggestion: If that is the case then you can use just the first 7 characters fo the commit hash

2023-08-10 16:12 UTC, josebui commented on package.json
> +    "terraso-backend": "github:techmatters/terraso-backend#a431376f71fe8537df6976cf8c2f6772e8d659af",
Issue: I don't see the package-lock.json file updated, you need to execute `npm install` for that

2023-08-16 20:11 UTC, david-code approved these changes

2023-08-21 16:01 UTC, josebui approved these changes

2023-08-21 16:39 UTC, merged